const coffeeData = {
    ol: [
        { sku: '', name: '부에노스 아이리스 룽고' },
        { sku: '', name: '볼루토' },
        { sku: '', name: '코지' },
        { sku: '', name: '에티오피아' },
        { sku: '', name: '니카라과' },
        { sku: '', name: '카프리치오' },
        { sku: '', name: '상하이 룽고' },
        { sku: '', name: '리반토' },
        { sku: '', name: '비엔나 룽고' },
        { sku: '', name: '파리' },
        { sku: '', name: '콜롬비아' },
        { sku: '', name: '도쿄 룽고' },
        { sku: '', name: '스톡홀룸' },
        { sku: '', name: '베네치아' },
        { sku: '', name: '인도네시아' },
        { sku: '', name: '로마' },
        { sku: '', name: '아르페지오' },
        { sku: '', name: '케이프타운 룽고' },
        { sku: '', name: '리스트레토' },
        { sku: '', name: '인디아' },
        { sku: '', name: '카자르' },
        { sku: '', name: '나폴리' },
    ],
    vl: [
        { sku: '', name: '솔레리오' },
        { sku: '', name: '볼테소' },
        { sku: '', name: '비앙코 도피오 포 밀크' },
        { sku: '', name: '이니지오' },
        { sku: '', name: '에티오피아' },
        { sku: '', name: '하프 카페나토' },
        { sku: '', name: '돌체' },
        { sku: '', name: '콜롬비아' },
        { sku: '', name: '엘살바도르' },
        { sku: '', name: '멜로지오' },
        { sku: '', name: '오라피오' },
        { sku: '', name: '블론드 로스트' },
        { sku: '', name: '베란다' },
        { sku: '', name: '아이스 레제로' },
        { sku: '', name: '코스타리카' },
        { sku: '', name: '아론디오' },
        { sku: '', name: '피콜로 포 밀크' },
        { sku: '', name: '멕시코' },
        { sku: '', name: '파이크 플레이스' },
        { sku: '', name: '콜롬비아' },
        { sku: '', name: '오다치오' },
        { sku: '', name: '아이스 포르테' },
        { sku: '', name: '스토미오' },
        { sku: '', name: '포르타도' },
        { sku: '', name: '키아로' },
        { sku: '', name: '베로나' },
        { sku: '', name: '인텐소' },
        { sku: '', name: '알티시오' },
        { sku: '', name: '리스트레토 클래시코' },
        { sku: '', name: '에스프레소 로스트' },
        { sku: '', name: '스쿠로' },
        { sku: '', name: '일카페' },
    ],
};
